//#region consts 
const botao = document.querySelector("#botao");
const botao2 = document.querySelector("#botao2");
const torterras = document.querySelector("#torterras");
const infernapes = document.querySelector("#infernapes");
const empoleons = document.querySelector("#empoleons");
const staraptors = document.querySelector("#staraptors");
const bibarels = document.querySelector("#bibarels");
const kricketunes = document.querySelector("#kricketunes");
const luxrays = document.querySelector("#luxrays");
const roserades = document.querySelector("#roserades");
const rampardoss = document.querySelector("#rampardoss");
const bastiodons = document.querySelector("#bastiodons");
const vespiquens = document.querySelector("#vespiquens");
const pachirisus = document.querySelector("#pachirisus");
const floatzels = document.querySelector("#floatzels");
const gastrodons = document.querySelector("#gastrodons");
const ambipoms = document.querySelector("#ambipoms");
const drifblims = document.querySelector("#drifblims");
const lopunnys = document.querySelector("#lopunnys");
const mismagiuss = document.querySelector("#mismagiuss");
const bronzongs = document.querySelector("#bronzongs");
const spiritombs = document.querySelector("#spiritombs");
const garchomps = document.querySelector("#garchomps");
const lucarios = document.querySelector("#lucarios");
const hippowdowns = document.querySelector("#hippowdowns");
const drapions = document.querySelector("#drapions");
const toxicroaks = document.querySelector("#toxicroaks");
const carnivines = document.querySelector("#carnivines");
const abomasnows = document.querySelector("#abomasnows");
const weaviles = document.querySelector("#weaviles");
const magnezones = document.querySelector("#magnezones");
const rhyperiors = document.querySelector("#rhyperiors");
const tangrowths = document.querySelector("#tangrowths");
const electivires = document.querySelector("#electivires");
const magmortars = document.querySelector("#magmortars");
const togekisss = document.querySelector("#togekisss");
const leafeons = document.querySelector("#leafeons");
const glaceons = document.querySelector("#glaceons");
const gliscors = document.querySelector("#gliscors");
const mamoswines = document.querySelector("#mamoswines");
const gallades = document.querySelector("#gallades");
const probopasss = document.querySelector("#probopasss");
const dusknoirs = document.querySelector("#dusknoirs");
const froslasss = document.querySelector("#froslasss");
const uxies = document.querySelector("#uxies");
const mesprits = document.querySelector("#mesprits");
const azelfs = document.querySelector("#azelfs");
const dialgas = document.querySelector("#dialgas");
const palkias = document.querySelector("#palkias");
const heatrans = document.querySelector("#heatrans");
const regigigass = document.querySelector("#regigigass");
const giratinas = document.querySelector("#giratinas");
const cresselias = document.querySelector("#cresselias");
const darkrais = document.querySelector("#darkrais");
const shaymins = document.querySelector("#shaymins");
const arceuss = document.querySelector("#arceuss");
//#endregion

//#region troca
botao.addEventListener("click", function() {
    torterras.setAttribute("src", "torterras.png");
    infernapes.setAttribute("src", "infernapes.png");
    empoleons.setAttribute("src", "empoleons.png");
    staraptors.setAttribute("src", "staraptors.png");
    bibarels.setAttribute("src", "bibarels.png");
    kricketunes.setAttribute("src", "kricketunes.png");
    luxrays.setAttribute("src", "luxrays.png");
    roserades.setAttribute("src", "roserades.png");
    rampardoss.setAttribute("src", "rampardoss.png");
    bastiodons.setAttribute("src", "bastiodons.png");
    vespiquens.setAttribute("src", "vespiquens.png");
    pachirisus.setAttribute("src", "pachirisus.png");
    floatzels.setAttribute("src", "floatzels.png");
    gastrodons.setAttribute("src", "gastrodons.png");
    ambipoms.setAttribute("src", "ambipoms.png");
    drifblims.setAttribute("src", "drifblims.png");
    lopunnys.setAttribute("src", "lopunnys.png");
    mismagiuss.setAttribute("src", "mismagiuss.png");
    bronzongs.setAttribute("src", "bronzongs.png");
    spiritombs.setAttribute("src", "spiritombs.png");
    garchomps.setAttribute("src", "garchomps.png");
    lucarios.setAttribute("src", "lucarios.png");
    hippowdowns.setAttribute("src", "hippowdowns.png");
    drapions.setAttribute("src", "drapions.png");
    toxicroaks.setAttribute("src", "toxicroaks.png");
    carnivines.setAttribute("src", "carnivines.png");
    abomasnows.setAttribute("src", "abomasnows.png");
    weaviles.setAttribute("src", "weaviles.png");
    magnezones.setAttribute("src", "magnezones.png");
    rhyperiors.setAttribute("src", "rhyperiors.png");
    tangrowths.setAttribute("src", "tangrowths.png");
    electivires.setAttribute("src", "electivires.png");
    magmortars.setAttribute("src", "magmortars.png");
    togekisss.setAttribute("src", "togekisss.png");
    leafeons.setAttribute("src", "leafeons.png");
    glaceons.setAttribute("src", "glaceons.png");
    gliscors.setAttribute("src", "gliscors.png");
    mamoswines.setAttribute("src", "mamoswines.png");
    gallades.setAttribute("src", "gallades.png");
    probopasss.setAttribute("src", "probopasss.png");
    dusknoirs.setAttribute("src", "dusknoirs.png");
    froslasss.setAttribute("src", "froslasss.png");
    uxies.setAttribute("src", "uxies.png");
    mesprits.setAttribute("src", "mesprits.png");
    azelfs.setAttribute("src", "azelfs.png");
    dialgas.setAttribute("src", "dialgas.png");
    palkias.setAttribute("src", "palkias.png");
    heatrans.setAttribute("src", "heatrans.png");
    regigigass.setAttribute("src", "regigigass.png");
    giratinas.setAttribute("src", "giratinas.png");
    cresselias.setAttribute("src", "cresselias.png");
    darkrais.setAttribute("src", "darkrais.png");
    shaymins.setAttribute("src", "shaymins.png");
    arceuss.setAttribute("src", "arceuss.png");
});
//#endregion

//#region
botao2.addEventListener("click", function() {
    garchomps.setAttribute("src", "garchompm.gif");
    lucarios.setAttribute("src", "lucariom.gif");
    abomasnows.setAttribute("src", "abomasnowm.gif");
    gallades.setAttribute("src", "galladem.gif");
    palkias.setAttribute("src", "palkiam.gif");
    dialgas.setAttribute("src", "dialgam.gif");
    giratinas.setAttribute("src", "giratinam.gif");
});
//#endregion